spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_DIR
              value: /deployments
            - name: SSO_URL
              value: ${SSO_URL}/auth
            - name: REALM
              value: ${REALM}
            - name: REALM_PUBLIC_KEY
              value: ${REALM_PUBLIC_KEY}
            - name: CLIENT_ID
              value: ${CLIENT_ID}
            - name: SECRET
              value: ${SECRET}
            - name: SSO_REALM
              valueFrom:
                configMapKeyRef:
                  name: sso-config
                  namespace: ${fabric8.namespace}
                  key: sso.realm
            - name: SSO_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: sso-config
                  namespace: ${fabric8.namespace}
                  key: sso.auth-server-url
            - name: JAVA_OPTIONS
              value: -Dsso.realm=$(SSO_REALM) -Dsso.auth-server-url=$(SSO_AUTH_SERVER_URL)

